# Generated by Django 2.2.4 on 2020-09-10 16:17

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('cournot', '0005_auto_20200910_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='history',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
    ]
